# Generated by Django 2.2.6 on 2019-10-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='filename',
            field=models.CharField(default='filenamedefault', max_length=255),
        ),
    ]
