# Generated by Django 2.2.6 on 2019-10-26 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0002_color_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 18, 48, 34, 420940)),
        ),
    ]
