# Generated by Django 2.2.6 on 2019-10-26 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('colors', '0003_color_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
